In [ ]:
import numpy as np
import pandas as pd

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("Salary_Data.csv")

df.head(10)

Saving Salary_Data.csv to Salary_Data (1).csv

  Education Level              Job Title  Years of Experience    Salary
0      Bachelor's      Software Engineer                  5.0   90000.0
1        Master's           Data Analyst                  3.0   65000.0
2             PhD         Senior Manager                 15.0  150000.0
3      Bachelor's        Sales Associate                  7.0   60000.0
4        Master's               Director                 20.0  200000.0
5      Bachelor's      Marketing Analyst                  2.0   55000.0
6        Master's        Product Manager                 12.0  120000.0
7      Bachelor's          Sales Manager                  4.0   80000.0
8      Bachelor's  Marketing Coordinator                  1.0   45000.0
9             PhD       Senior Scientist                 10.0  110000.0

In [ ]:
df.tail(5)

,Education Level,Job Title,Years of Experience,Salary
370,Bachelor's,Senior Marketing Analyst,8.0,85000.0
371,Master's,Director of Operations,19.0,170000.0
372,Bachelor's,Junior Project Manager,2.0,40000.0
373,Bachelor's,Senior Operations Coordinator,7.0,90000.0
374,PhD,Senior Business Analyst,15.0,150000.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375 entries, 0 to 374
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Education Level      373 non-null    object
 1   Job Title            373 non-null    object
 2   Years of Experience  373 non-null    float64
 3   Salary               373 non-null    float64
dtypes: float64(2), object(2)
memory usage: 11.8+ KB

In [ ]:
print("Shape:", df.shape)

Shape: (375, 4)

In [ ]:
print("Columns:")
print(df.columns)

Columns:
Index(['Education Level', 'Job Title', 'Years of Experience', 'Salary'], dtype='object')

In [ ]:
print(df.describe())

       Years of Experience         Salary
count           373.000000     373.000000
mean             10.030831  100577.345845
std               6.557007   48240.013482
min               0.000000     350.000000
25%               4.000000   55000.000000
50%               9.000000   95000.000000
75%              15.000000  140000.000000
max              25.000000  250000.000000

In [ ]:
df.isnull().sum()

Education Level        2
Job Title              2
Years of Experience    2
Salary                 2
dtype: int64

In [ ]:
df["Bonus"] = df["Salary"] * 0.10

print(df.head())

  Education Level          Job Title  Years of Experience    Salary    Bonus
0      Bachelor's  Software Engineer                  5.0   90000.0   9000.0
1        Master's       Data Analyst                  3.0   65000.0   6500.0
2             PhD     Senior Manager                 15.0  150000.0  15000.0
3      Bachelor's    Sales Associate                  7.0   60000.0   6000.0
4        Master's           Director                 20.0  200000.0  20000.0

In [ ]:

df["Salary"] = df["Salary"] * 1.05

print(df.head())

  Education Level          Job Title  Years of Experience    Salary    Bonus
0      Bachelor's  Software Engineer                  5.0   94500.0   9000.0
1        Master's       Data Analyst                  3.0   68250.0   6500.0
2             PhD     Senior Manager                 15.0  157500.0  15000.0
3      Bachelor's    Sales Associate                  7.0   63000.0   6000.0
4        Master's           Director                 20.0  210000.0  20000.0